import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowRight, LockKeyhole } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/login")({ head: () => ({ meta: [{ title: "Sign in — Sahayak" }, { name: "description", content: "Sign in to continue your government benefit journey with Sahayak." }, { property: "og:title", content: "Sign in — Sahayak" }, { property: "og:description", content: "Continue your Sahayak benefit journey." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: LoginPage });

function LoginPage() { return <AuthLayout title="Welcome back" description="Continue your journey from eligibility to action."><Card className="border-line bg-card shadow-none"><CardHeader><div className="grid size-10 place-items-center rounded-lg bg-brand/10 text-brand"><LockKeyhole className="size-5" /></div><CardTitle className="mt-4 font-display text-2xl">Sign in to Sahayak</CardTitle><p className="text-sm text-muted-foreground">Demo mode is ready — no real account required.</p></CardHeader><CardContent><form className="space-y-4" onSubmit={(event) => event.preventDefault()}><label className="block text-sm font-medium">Mobile number or email<Input className="mt-2 bg-card" placeholder="rahul@example.com" /></label><label className="block text-sm font-medium">Password<Input className="mt-2 bg-card" type="password" placeholder="••••••••" /></label><Button type="submit" className="w-full">Continue <ArrowRight /></Button></form><Button asChild variant="outline" className="mt-3 w-full bg-card"><Link to="/demo">Enter demo mode</Link></Button><p className="mt-5 text-center text-sm text-muted-foreground">New to Sahayak? <Link to="/signup" className="font-medium text-brand hover:underline">Create an account</Link></p></CardContent></Card></AuthLayout>; }

function AuthLayout({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="grid min-h-screen place-items-center bg-ice-2 px-5 py-10"><div className="w-full max-w-md"><Link to="/" className="mb-8 flex items-center justify-center gap-2.5"><span className="grid size-9 place-items-center rounded-lg bg-brand font-display text-sm font-semibold text-primary-foreground">S</span><span className="font-display text-lg font-semibold">Sahayak</span></Link><div className="mb-6 text-center"><h1 className="font-display text-3xl font-semibold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{description}</p></div>{children}<p className="mt-6 text-center text-xs text-muted-foreground">Your sensitive decisions stay yours.</p></div></div>; }